---
title: "Visualization Project"
author: "Michael Polonskiy"
date: "`r format(Sys.time(), "%Y-%m-%d")`"  
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide  
    highlight: tango
    number_sections: false
---

```{r libraries}

library(reticulate)
library(tidyverse)
library(Metrics)
Sys.setenv(RETICULATE_PYTHON = here::here("~/.virtualenvs/VisualizationProject/Scripts/python.exe"))
#reticulate::virtualenv_install("VisualizationProject", packages =c("pandas","numpy"))
reticulate::use_virtualenv("VisualizationProject")
```



```{r}
source_python("Data Processing.py")
df <- py$df

```


```{r, warnings=FALSE}
library(tidyverse)
library(GGally)
library(jtools)
library(ggpubr)
library(rworldmap)
library(ggplot2)
library(scales)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(gghighlight)
library(ggsflabel)
library(ggtext)
library(lubridate)
library(RColorBrewer)
library(scales)
```


Although Pre-processing is done in python we will create the main metrics used in this analysis in r, since it is easier to use the functions provided in r for this task once the dataset is pre-processed.

```{r}
df$ScaledRating <- rescale((0.5 * scale(df$ProcessorRating, center=FALSE) + 0.25 * scale(df$G2Dmark, center=FALSE) + 0.25 * scale(df$G3Dmark, center=FALSE)), to=c(1,100))
df$PricePerformance <- ( df$Price_euros / df$ScaledRating ) 
df$ScaledGPU <-  rescale( scale(df$G3Dmark, center=FALSE) +  scale(df$G2Dmark, center=FALSE), to=c(1,100))
df$ScaledCPU <- rescale( df$ProcessorRating, to=c(1,100))
df$RatingBin <- cut(df$ScaledRating, breaks=c(0,10,20, 30, 40, 50,60,70,80,90,100), labels=FALSE)
df$Ram <- as.numeric(df$Ram)
df$combinations = paste0(df$Cpu,' ',df$Gpu)


```



```{r}
#Main Theme object and colors

 theme <- theme_bw() + theme(plot.title = element_text(hjust = 0.5), plot.title.position = 'panel', text = element_text(size = 13, color="black"), axis.text.x = element_text(size = 13, color="black"),  axis.text.y = element_text(size = 13, color="black"),  axis.title.y = element_text(size = 14, color="black"),  axis.title.x = element_text(size = 14, color="black"), legend.title=element_text(size = 14, color="black"), legend.text=element_text(size = 13, color="black")) 

colorsinv = c("green4", "green1", "yellow3","red1", "red4")
colors = c("red4", "red1", "yellow3", "green1", "green4")

```


```{r}
df %>% group_by(OpSys) %>% summarise(price_mean = mean(Price_euros), price_sd=sd(Price_euros)) %>%  ggplot(aes(x=reorder(OpSys,-price_mean), y=price_mean)) + geom_bar(stat="identity") +   geom_errorbar(aes(ymin=price_mean-price_sd, ymax=price_mean+price_sd)) + coord_flip()

```


```{r}
df %>% group_by(OpSys, TypeName) %>% summarise(n = n()) %>% filter(n > 10) %>%  ggplot(aes(x=OpSys, y=n, color=TypeName, fill=TypeName)) + geom_bar(stat="identity", position="fill") + coord_flip()
```


```{r, fig.width=12, fig.height=12}

library(corrplot)

colnames(df)

dfnum <- df[c("ScreenResolution", "Inches","Ram","Weight",
       "Price_euros", "ProcessorRating","G3Dmark","G2Dmark", "Memory1", "Memory2",
       "Memory1HDD", "Memory1SSD", "Memory2HDD", "Memory2SSD")]

dfnum$Ram <- as.numeric(dfnum$Ram)

ggcorr(dfnum)
```


```{r}
df %>% group_by(Product) %>%  summarise(Priced_euros=mean(Price_euros), Scaled_GPU = mean(ScaledGPU)) %>% arrange(Priced_euros) %>% slice(81:85)
```




```{r, fig.width=12, fig.height=12}
subset <- bind_rows(df %>% group_by(Product) %>%  summarise(Priced_euros=mean(Price_euros),ScaledGPU=mean(ScaledGPU), ScaledCPU=mean(ScaledCPU)) %>% arrange(-Priced_euros) %>% head(5), 
                    df %>% group_by(Product) %>%  summarise(Priced_euros=mean(Price_euros),ScaledGPU=mean(ScaledGPU), ScaledCPU=mean(ScaledCPU)) %>% arrange(Priced_euros) %>% slice(81:85))


df %>% ggplot(aes(x=ScaledGPU, y=ScaledCPU)) + geom_point(aes(color=Price_euros, size=Price_euros)) + geom_smooth() +
  scale_color_gradientn(colors = colorsinv, n.breaks= 5) + scale_size_binned(n.breaks= 5) + scale_size(trans = "reverse") +

guides(color= guide_legend(), size=guide_legend()) +
  
  theme(plot.title = element_text(hjust = 0.5), plot.title.position = 'panel') +

  geom_label_repel( data=subset, aes(label = Product), size = 5, color = alpha("black", 0.8),
                    force = 50, seed = 20, min.segment.length = 0.1, segment.curvature = -0.4, 
                    segment.size = 1, segment.color = "black", arrow = arrow(length = unit(0.015, "npc"),
                    ends = "last", type = "closed"), fill = alpha("transparent", .3), max.overlaps = 10)  +  
 
  labs(title = "Relation between GPU and CPU performance linked to the laptop price", color="Price", size="Price", x="GPU Score", y="CPU Score") +
  
  theme



```

```{r, fig.width=12, fig.height=12}

df %>% group_by(RatingBin) %>% summarise(price_mean = mean(Price_euros), price_sd=sd(Price_euros), n=n()) %>% filter(n > 10) %>%  ggplot(aes(x=RatingBin, y=price_mean)) + geom_bar(stat="identity") +   geom_errorbar(aes(ymin=price_mean-price_sd, ymax=price_mean+price_sd)) + geom_smooth(smoothing=FALSE)

```
```{r, fig.width=12, fig.height=8}
topn <- 10
total <- count(df)$n

df %>% group_by(Cpu) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% group_by(Cpu = factor(c(Cpu[1:topn ], rep("Other", n() - topn)), levels=c("Other",Cpu[topn:1]))) %>% group_by(Cpu) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) %>% ggplot(aes(x=Cpu, y=percentage, fill=meanPricePerformance)) + geom_bar(stat="identity") + coord_flip() +  scale_fill_gradientn(colors = c("green4", "green1", "yellow3","red1", "red4"), n.breaks= 5) + geom_label(aes(label=round(percentage,2)))

```

```{r, fig.width=14,fig.height=12}
topn <- 10
total <- count(df)$n

df %>% group_by(Gpu) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% group_by(Gpu = factor(c(Gpu[1:topn ], rep("Other", n() - topn)), levels=c("Other",Gpu[topn:1]))) %>% group_by(Gpu) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) %>% ggplot(aes(x=Gpu, y=percentage, fill=meanPricePerformance)) + geom_bar(stat="identity") + coord_flip() +  scale_fill_gradientn(colors = c("green4", "green1", "yellow3","red1", "red4"), n.breaks= 5) + geom_label(aes(label=round(percentage,2)))


```


```{r}
subset <- df %>% group_by(combinations) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% group_by(combinations = factor(c(combinations[1:topn ], rep("Other", n() - topn)), levels=c("Other",combinations[topn:1]))) %>% group_by(combinations) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) %>% top_n(5)



df %>% group_by(combinations) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% group_by(combinations = factor(c(combinations[1:topn ], rep("Other", n() - topn)), levels=c("Other",combinations[topn:1]))) %>% group_by(combinations) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) %>% ggplot(aes(x=combinations, y=percentage, fill=meanPricePerformance)) + geom_bar(stat="identity") + coord_flip() +  scale_fill_gradientn(colors = c("green4", "green1", "yellow3","red1", "red4"), n.breaks= 5) + geom_label_repel(data=subset, aes(label=combinations), size = 5, color = alpha("black", 0.8),
                    force = 50, seed = 20, min.segment.length = 0.1, segment.curvature = -0.4, 
                    segment.size = 1, segment.color = "black", arrow = arrow(length = unit(0.015, "npc"),
                    ends = "last", type = "closed"), fill = alpha("transparent", .3), max.overlaps = 10) + theme(axis.title.y=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank())




```


```{r}

df %>% group_by(Company) %>% summarise(meanRating = mean(ScaledRating), n = n()) %>% filter(n > 10) %>% ggplot(aes(x=reorder(Company, meanRating), y=meanRating)) + geom_bar(stat="identity")


```

```{r}
df  %>%  filter(Company == c("MSI","Asus", "Dell", "Acer","Lenovo","HP","Toshiba")) %>%  ggplot(aes(x=Company, y=PricePerformance, fill=Company, color=Company)) +
geom_bar(stat="identity")



```
```{r, fig.width=16, fig.height=10}
df  %>%  filter(Company == c("MSI","Asus", "Dell", "Acer","Lenovo","HP","Toshiba")) %>%  ggplot(aes(Price_euros, fill=Company, color=Company)) +
  geom_density() + facet_wrap(vars(Company))
```



```{r}
model1 <- lm(PricePerformance ~ Weight + Memory1 + Memory2 + ScreenResolution + Ram,data=df)
jtools::plot_summs(model1,scale=TRUE)

```

```{r}

df %>% group_by(OpSys) %>% summarise(price_mean = mean(PricePerformance), price_sd=sd(PricePerformance), n=n()) %>% filter(n > 10) %>%  ggplot(aes(x=reorder(OpSys,-price_mean), y=price_mean)) + geom_bar(stat="identity") +   geom_errorbar(aes(ymin=price_mean-price_sd, ymax=price_mean+price_sd))


```


```{r}
df %>%   ggplot(aes(x=Price_euros, y=ScaledRating)) + geom_line(stat="identity") 
```


```{r}
subset <- df %>% group_by(combinations) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% 
                 group_by(combinations = factor(c(combinations[1:topn ], rep("Other", n() - topn)), levels=c("Other",combinations[topn:1]))) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) %>% top_n(5)



data <- df %>% group_by(combinations) %>% summarise(n=n(), meanPricePerformance = mean(PricePerformance)) %>% arrange(desc(n)) %>% 
        group_by(combinations = factor(c(combinations[1:topn ], rep("Other", n() - topn)), levels=c("Other",combinations[topn:1]))) %>% 
        group_by(combinations) %>% summarise(n=sum(n) , meanPricePerformance = mean(meanPricePerformance), percentage=n/total * 100)  %>% arrange(desc(n)) 

data %>% ggplot(aes(x=combinations, y=percentage, fill=meanPricePerformance)) + 
  
         geom_bar(stat="identity") + coord_flip() +  scale_fill_gradientn(colors = colorsinv, n.breaks= 5) +
  
         geom_label(aes(label=round(percentage,2)), fill="white") +   
  
         labs(title = "Figure 5: Top 10 used Hardware Specs with Price Performance Ratio", fill="Price Performance\nRatio", y="Percentage of usage in Devices", x="Hardware") +
  
         theme

```









