---
title: "Visualization Project"
author: "Michael Polonskiy"
date: "`r format(Sys.time(), "%Y-%m-%d")`"  
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide  
    highlight: tango
    number_sections: false
---

```{r libraries}

library(reticulate)
library(tidyverse)
library(Metrics)
Sys.setenv(RETICULATE_PYTHON = here::here("~/.virtualenvs/VisualizationProject/Scripts/python.exe"))
#reticulate::virtualenv_install("VisualizationProject", packages =c("pandas","numpy"))
reticulate::use_virtualenv("VisualizationProject")
```



```{r}
source_python("Data Processing.py")
df <- py$df

```


```{r, warnings=FALSE}
library(tidyverse)
library(GGally)
library(jtools)
library(ggpubr)
library(rworldmap)
library(ggplot2)
library(scales)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(gghighlight)
library(ggsflabel)
library(ggtext)
library(lubridate)
library(RColorBrewer)
library(scales)
```

```{r}
df %>% group_by(OpSys) %>% summarise(price_mean = mean(Price_euros), price_sd=sd(Price_euros)) %>%  ggplot(aes(x=reorder(OpSys,-price_mean), y=price_mean)) + geom_bar(stat="identity") +   geom_errorbar(aes(ymin=price_mean-price_sd, ymax=price_mean+price_sd)) + coord_flip()

```
```{r}
df %>% group_by(OpSys, Company) %>% summarise(n = n()) %>%  ggplot(aes(x=OpSys, y=n, color=Company, fill=Company)) + geom_bar(stat="identity", position="fill") + coord_flip()
```


```{r, fig.width=12, fig.height=12}

library(corrplot)

colnames(df)

dfnum <- df[c("ScreenResolution", "Inches","Ram","Weight",
       "Price_euros", "ProcessorRating","G3Dmark","G2Dmark", "Memory1", "Memory2",
       "Memory1HDD", "Memory1SSD", "Memory2HDD", "Memory2SSD")]

dfnum$Ram <- as.numeric(dfnum$Ram)

corrplot(cor(dfnum), method = 'number')
```
```{r}


df$ScaledRating <- rescale((0.5 * scale(df$ProcessorRating, center=FALSE) + 0.25 * scale(df$G2Dmark, center=FALSE) + 0.25 * scale(df$G3Dmark, center=FALSE)), to=c(1,100))
df$PricePerformance <- ( df$Price_euros / df$ScaledRating ) 

```


